### ISSUE TITLE
Hack'n'Plan Github Integration

### ISSUE THREAD

**Issue by SkeleKing042** [SkeleKing042/ILOVEYOU-GAME#12]
hnp-16
this is a test, plz ignore

**Comment by Aidan-AIE** [comment]
I am not going to ignore this

**Comment by SkeleKing042** [comment]
hnp-203

**Comment by SkeleKing042** [comment]
# Summary
Github commit comments can reference HNP task. To do so, simply add "hnp-###" anywhere in the commit message.
