### ISSUE TITLE
Tasks not appearing.

### ISSUE THREAD

**Issue by SkeleKing042** [SkeleKing042/ILOVEYOU-GAME#176]
The auto discard function seems to cause issues if tasks get completed too fast or card are quickly chosen. I think this might be an issue with the order of operations.

**Comment by SkeleKing042** [comment]
![image](https://github.com/user-attachments/assets/c1c05508-c13c-4cb4-9e7a-ac270878ba38)

**Comment by Aidan-AIE** [comment]
Wow I love Naruto 🤩🤩🤩🤩🤩🤩🤩
